### PR TITLE
pass settings as hash to Client and allow it to resolve security 

### PR DESCRIPTION
**Pull request by timothy-volvo**
Fix for [Issue 54](https://github.com/joshdholtz/fastlane-plugin-s3/issues/54)

Pass the configuration as a hash to the client rather then instantiating the Credentials and setting the global config.

This allows the client to resolve settings such as role_arn from the config and credentials file

### CODE REVIEW

**Comment by JesseScott** [comment]
@timothy-volvo Conflicts

**Comment by svanzoest** [comment]
@joshdholtz it would be great to have this merged.

**Comment by zachawilson** [comment]
This LGTM! Can this be merged?
@joshdholtz

**Comment by viacheslavleonov** [comment]
@joshdholtz Could you merge this PR?

**Review by joshdholtz — APPROVED** [review]
This is great! Thank you soooo much for making this change ❤️ Sorry this sat for so long 😔 I have my life in check now and these PRs will have higher priority now 💪

**Pull request merged**
