### PR TITLE
aws-sdk version bump to v3

### LINKED ISSUE #71: Update aws-sdk version
Hi here!

In my project, I use aws-sdk-s3, which is v3 version of api. Your incredible plugin depends on aws-sdk v2 `~> 2.3`, which is incompatible by gem dependency resolver. Would you be open for PR with bump version of aws sdk and necessary code changes? Or it could be a reason why version bump is not acceptable?

Thanks!

### PR DESCRIPTION
**Pull request by jaximan**
Resolves #71.

### CODE REVIEW

**Comment by jackyLianMT** [comment]
Please merge this pr as the fastlane 2.144 is now switching to aws-sdk v3. Having this plugin on v2 leads to a dependency conflict issue

```
 fastlane-plugin-aws_s3 was resolved to 1.6.1, which depends on
      aws-sdk (~> 2.3) was resolved to 2.3.0, which depends on
        aws-sdk-resources (= 2.3.0) was resolved to 2.3.0, which depends on
          aws-sdk-core (= 2.3.0)

    fastlane (~> 2.144) was resolved to 2.144.0, which depends on
      aws-sdk-s3 (~> 1.0) was resolved to 1.61.1, which depends on
        aws-sdk-core (~> 3, >= 3.83.0)
```

**Comment by jaximan** [comment]
@jackyLianMT I can rebase PR with latest master, but still looking for reviewer :(

**Comment by levibostian** [comment]
@jaximan, I have a new PR made [here](https://github.com/fastlane-community/fastlane-plugin-s3/pull/85/) to do what you have done with this PR. I am pointing this out if you want to avoid having to rebase.

**Comment by joshdholtz** [comment]
Closing this since this was completed in #81 when _fastlane_ also changed to using v3. Thanks for the PR thought! ❤️

**Pull request closed without merging**
