### PR TITLE
support alternate download endpoint urls

### PR DESCRIPTION
**Pull request by dlethin**
This fix is meant to address #47

### CODE REVIEW

**Comment by ctaintor** [comment]
It'd also be useful to provide the replacement regex. I have the same need as what you're saying, but my reverse proxy chops off more of the URL ( e.g. https://S3/bucket-name/asdf/* -> https://mysite.com/*)

**Comment by ctaintor** [comment]
@dlethin - sent you a [PR](https://github.com/simplisafe/fastlane-plugin-s3/pull/1) to support this

**Comment by duro** [comment]
@ctaintor Any reason this was never merged. As I mentioned in #4 this would solve my problem of protecting my builds.

**Comment by duro** [comment]
For what it counts, I have pulled this fork into my project and it works flawlessly. Thanks!!

**Comment by JesseScott** [comment]
@dlethin merge conflicts - maybe sync with upstream and refresh the PR ? 🙏

**Comment by siddarthgandhi** [comment]
PR synced with upstream.

**Comment by mikecsmith** [comment]
Any chance of this being merged? I would absolutely love this functionality due to my S3 bucket being hosted behind Cloudfront and not being publicly accessible.

**Comment by omerduzyol** [comment]
I also need this feature as I've different public URLs for objects uploaded.

**Comment by jonlay-hanno** [comment]
I also have a need for exactly this feature - Cloudfront seems to be the preferred way to share releases on S3 as it makes it a lot easier to add security features to control access to the assets. Our configuration means that the files are not actually accessible from the direct S3 URL at all.

I forked this branch and updated with the latest commits from the upstream master, to verify:
https://github.com/jonlay-hanno/fastlane-plugin-s3/tree/feature/optional-download-endpoint-update

Another confirmation on my end that the updated code works perfectly in my tests of a live app that we’re releasing.

@joshdholtz is there anything I can do to help get this merged? Happy to update the README with a better example, also, if that's blocking in any way.

**Comment by joshdholtz** [comment]
I will take a look at this today! Just need to get a cup of ☕️ in my first 😊

**Comment by jonlay-hanno** [comment]
Hey @joshdholtz - you are probably super busy with much more important things than this PR - just checking in to see whether there's any likelihood of this being merged.

I'll go down the hacky route if not, but would love to see this "natively" in fastlane_s3 if possible 😄

**Comment by joshdholtz** [comment]
Let me get some coffee in me and then I’ll take a look at this PR!

**Review by joshdholtz — APPROVED** [review]
This looks great to me! Sorry for slow reply on this. No excuses but I have a my life sorted out now so I will be much faster going forward 😊

**Comment by hanno-jonlay** [comment]
🙌 Always appreciated. Thanks for all the time you put into this stuff.

**Pull request merged**
